const zodiac = [
  {
    name: "Aries",
    start_date: "March 21",
    end_date: "April 19",
    element: "Fire",
    quality: "Cardinal",
    ruling_planet: "Mars",
  },
  {
    name: "Taurus",
    start_date: "April 20",
    end_date: "May 20",
    element: "Earth",
    quality: "Fixed",
    ruling_planet: "Venus",
  },
  {
    name: "Gemini",
    start_date: "May 21",
    end_date: "June 20",
    element: "Air",
    quality: "Mutable",
    ruling_planet: "Mercury",
  },
  {
    name: "Cancer",
    start_date: "June 21",
    end_date: "July 22",
    element: "Water",
    quality: "Cardinal",
    ruling_planet: "Moon",
  },
  {
    name: "Leo",
    start_date: "July 23",
    end_date: "August 22",
    element: "Fire",
    quality: "Fixed",
    ruling_planet: "Sun",
  },
  {
    name: "Virgo",
    start_date: "August 23",
    end_date: "September 22",
    element: "Earth",
    quality: "Mutable",
    ruling_planet: "Mercury",
  },
  {
    name: "Libra",
    start_date: "September 23",
    end_date: "October 22",
    element: "Air",
    quality: "Cardinal",
    ruling_planet: "Venus",
  },
  {
    name: "Scorpio",
    start_date: "October 23",
    end_date: "November 21",
    element: "Water",
    quality: "Fixed",
    ruling_planet: "Pluto",
  },
  {
    name: "Sagittarius",
    start_date: "November 22",
    end_date: "December 21",
    element: "Fire",
    quality: "Mutable",
    ruling_planet: "Jupiter",
  },
  {
    name: "Capricorn",
    start_date: "December 22",
    end_date: "January 19",
    element: "Earth",
    quality: "Cardinal",
    ruling_planet: "Saturn",
  },
  {
    name: "Aquarius",
    start_date: "January 20",
    end_date: "February 18",
    element: "Air",
    quality: "Fixed",
    ruling_planet: "Uranus",
  },
  {
    name: "Pisces",
    start_date: "February 19",
    end_date: "March 20",
    element: "Water",
    quality: "Mutable",
    ruling_planet: "Neptune",
  },
];
